In [16]:
import numpy as np
import pandas as pd

pima = pd.read_csv('./data/pima-indians-diabetes.csv')
pima.columns = ['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'bmi', 'diabetes_pedigree', 'age', 'outcome']

In [17]:
len(pima)

767

In [18]:
pima.size

6903

In [19]:
pima.isna().sum()

pregnancies          0
glucose              0
blood_pressure       0
skin_thickness       0
insulin              0
bmi                  0
diabetes_pedigree    0
age                  0
outcome              0
dtype: int64

In [20]:
pima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   pregnancies        767 non-null    int64  
 1   glucose            767 non-null    int64  
 2   blood_pressure     767 non-null    int64  
 3   skin_thickness     767 non-null    int64  
 4   insulin            767 non-null    int64  
 5   bmi                767 non-null    float64
 6   diabetes_pedigree  767 non-null    float64
 7   age                767 non-null    int64  
 8   outcome            767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [21]:
pima.describe().T

count        mean         std     min      25%      50%  \
pregnancies        767.0    3.842243    3.370877   0.000   1.0000    3.000   
glucose            767.0  120.859192   31.978468   0.000  99.0000  117.000   
blood_pressure     767.0   69.101695   19.368155   0.000  62.0000   72.000   
skin_thickness     767.0   20.517601   15.954059   0.000   0.0000   23.000   
insulin            767.0   79.903520  115.283105   0.000   0.0000   32.000   
bmi                767.0   31.990482    7.889091   0.000  27.3000   32.000   
diabetes_pedigree  767.0    0.471674    0.331497   0.078   0.2435    0.371   
age                767.0   33.219035   11.752296  21.000  24.0000   29.000   
outcome            767.0    0.348110    0.476682   0.000   0.0000    0.000   

                       75%     max  
pregnancies          6.000   17.00  
glucose            140.000  199.00  
blood_pressure      80.000  122.00  
skin_thickness      32.000   99.00  
insulin            127.500  846.00  
bmi                 36.600   67.10  
diabetes_pedigree    0.625    2.42  
age                 41.000   81.00  
outcome              1.000    1.00

In [22]:
pima.head()

pregnancies  glucose  blood_pressure  skin_thickness  insulin   bmi  \
0            1       85              66              29        0  26.6   
1            8      183              64               0        0  23.3   
2            1       89              66              23       94  28.1   
3            0      137              40              35      168  43.1   
4            5      116              74               0        0  25.6   

   diabetes_pedigree  age  outcome  
0              0.351   31        0  
1              0.672   32        1  
2              0.167   21        0  
3              2.288   33        1  
4              0.201   30        0

In [23]:
# pima.iloc[:, :len(pima.columns)-1].values
# pima.iloc[:, :7].values
# pima['diabetes_pedigree'].values
pima.iloc[:10, :7]
pima.loc[:10, 'diabetes_pedigree']

0     0.351
1     0.672
2     0.167
3     2.288
4     0.201
5     0.248
6     0.134
7     0.158
8     0.232
9     0.191
10    0.537
Name: diabetes_pedigree, dtype: float64

In [24]:
feature_names = ['pregnancies', 'glucose', 'blood_pressure', 'skin_thickness', 'insulin', 'bmi', 'diabetes_pedigree', 'age']
X = pima[feature_names].values
y = pima.outcome.values

# print(type(X), type(y))
print(X[:10], y[:10])

[[1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]
 [5.000e+00 1.160e+02 7.400e+01 0.000e+00 0.000e+00 2.560e+01 2.010e-01
  3.000e+01]
 [3.000e+00 7.800e+01 5.000e+01 3.200e+01 8.800e+01 3.100e+01 2.480e-01
  2.600e+01]
 [1.000e+01 1.150e+02 0.000e+00 0.000e+00 0.000e+00 3.530e+01 1.340e-01
  2.900e+01]
 [2.000e+00 1.970e+02 7.000e+01 4.500e+01 5.430e+02 3.050e+01 1.580e-01
  5.300e+01]
 [8.000e+00 1.250e+02 9.600e+01 0.000e+00 0.000e+00 0.000e+00 2.320e-01
  5.400e+01]
 [4.000e+00 1.100e+02 9.200e+01 0.000e+00 0.000e+00 3.760e+01 1.910e-01
  3.000e+01]] [0 1 0 1 0 1 0 1 1 0]


数据分割

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print(X_train)

[[1.00e+01 1.01e+02 7.60e+01 ... 3.29e+01 1.71e-01 6.30e+01]
 [1.00e+00 1.17e+02 8.80e+01 ... 3.45e+01 4.03e-01 4.00e+01]
 [2.00e+00 9.50e+01 5.40e+01 ... 2.61e+01 7.48e-01 2.20e+01]
 ...
 [7.00e+00 1.14e+02 6.40e+01 ... 2.74e+01 7.32e-01 3.40e+01]
 [6.00e+00 1.25e+02 7.60e+01 ... 3.38e+01 1.21e-01 5.40e+01]
 [2.00e+00 1.29e+02 7.40e+01 ... 3.32e+01 5.91e-01 2.50e+01]]


In [32]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_predict = logreg.predict(X_test)

/Users/zhougonglai/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
from sklearn.metrics import accuracy_score

score_test = accuracy_score(y_test, y_predict)
print(score_test)

0.7916666666666666
